### ISSUE TITLE
Emulated Hue Differences

### ISSUE THREAD

**Issue by drinfernoo** [marcelveldt/hassio-addons-repo#16]
Just curious, what is the difference between your Emulated Hue addon, and the standard `emulated_hue` integration?

**Comment by marcelveldt** [comment]
standard emulated hue does not fully emulate a Hue bridge but only a few parts. It was intentionally designed to get support for Alexa and Google Home working.
What I'm trying to do here is fully emulate the Hue bridge with the hass entities, so you can control Hue (compatible) apps and devices to control Home Assistant devices, most of all the entertainment mode.

I actually started by creating it as a drop-in replacement for the emulated_hue integration but that resulted in trouble because of the encryption and high packet rate so that's why it's an addon now.

**Comment by drinfernoo** [comment]
I kind of worked out that this seemed more feature-complete, but wasn't exactly sure what was the motivation 😅

Very nice!
