### ISSUE TITLE
Sign in with Google temporarily disabled for this app

### ISSUE THREAD

**Issue by code-muffin** [marcelveldt/hassio-addons-repo#8]
When starting the backup job with auto-upload of snapshots to Google drive, I get this error when trying to complete Google Authentication: 
<img width="759" alt="Screenshot 2019-12-08 at 15 55 53" src="https://user-images.githubusercontent.com/48162491/70391239-38cd6480-19d3-11ea-88d4-aa3ef1cc44c5.png">

Any ideas how to solve this?
thanks :)

**Comment by mmichalko** [comment]
I have the same problem...

**Comment by dominikmueller** [comment]
I do have a kind of workaround for this issue. It seems that Google disabled the OAuth Credentials provided in this file: [settings.yaml](https://github.com/marcelveldt/hassio-addons-repo/blob/master/autobackup/app/settings.yaml).

You can set up your own OAuth application credentials following this guide (and the steps below):
https://pythonhosted.org/PyDrive/quickstart.html

- Keep in mind that you need to enable billing for your GCP project.
You need to provide a payment method/credit card, but you won't get charged.
- Don't select "Web application" as application type - I selected "Other" and it works fine.

- You will get a client_id and a client_secret which you then can replace in the `settings.yaml` file on your hassio installation.
For my installation it was `/usr/share/hassio/addons/git/62c7908d/autobackup/app/settings.yaml`.
- Afterwards run "Rebuild" for the plugin and follow the process documented in the log output.
You might get a warning that your application is not validated by Google - but you can safely ignore/acknowledge it.

Lmk when you're still having trouble setting it up.

A better solution for this issue might be an updated Web UI where every user needs to provide his own client_id and client_secret since I think that Google always will block the credentials after some time.

**Comment by darekhome** [comment]
Is that something new in this 'add-on'? I have the same problem and rather wanted to avoid registering on some site providing 'credit-card' info...
As I have bad experience...

<img width="578" alt="don't give out credit card information online" src="https://user-images.githubusercontent.com/55238173/70868111-6723e480-1f7d-11ea-80de-f01d1d167291.png">

**Comment by dominikmueller** [comment]
It's nothing "new". You just can't use the provided credentials anymore.
So you can either try to use the provided credentials (that the add-on creator presumably created with his private google account - but which unfortunately don't work anymore) or provide the credentials by your own.
Or you can wait for the add-on creator to replace the provided credentials with valid ones.

Maybe its worth mentioning that "some site" actually is Google - so it would be pretty disastrous if they would treat their customers payment information in an unsafe way.

You shouldn't need to create a new account since you can use your Google Account (you just need to "register" it for the [Google Cloud Platform (GCP)](https://cloud.google.com/)) and enable the free-to-use Google Drive API (at least for 1,000,000,000 requests per day).

**Comment by marcelveldt** [comment]
I will have a look what's going on. Probably the free credit is all used and in that case it's indeed needed to create your own creds.

**Comment by patrezp** [comment]
@marcelveldt 
Can you maybe provide an option within autobackup to add your own oauth client ID and secret?

**Comment by xerxel** [comment]
Same problem... Will try to create own creds...

**Comment by xerxel** [comment]
> Same problem... Will try to create own creds...

Well, creating new creds worked for me. Thanks @dominikmueller However, I have a NOOB question... To edit the settings.yaml file, I logged in to the Supervisor using docker, found the file, copied it out of the container, edited it to replace credentials with mine, copied it back into the Supervisor docker then rebuilt the add-on, restarted it, logged into the app on port 8055 (via IP address), clicked the link to sign in to Google and auth then pasted the result back to the Add-on.

Everything is working great and a snapshot was created and automatically uploaded to Google Drive! So my question is, will the settings.yaml file still persist after Hass.io is rebooted or upgraded? **Have I just edited a file** within a container within a container **which will be blown away on next restart** or did I edit something which will be retained after a reboot?

**Comment by dominikmueller** [comment]
I think it will be gone when you're either reinstalling or upgrading the plugin. So everything that causes a rebuild of that container will most likely overwrite the changes and you might have the same issue again.

Just restarting the container should however not cause a rebuild (except hass.io is doing some "magic" stuff..).

For my part, I switched to another Google Drive Backup Plugin (https://github.com/sabeechen/hassio-google-drive-backup) which - so far - seems to be working without any modifications.

**Comment by xerxel** [comment]
ah-ha! Other plugin looks good. will switch to that. Apologies Marcel!

**Comment by marcelveldt** [comment]
No worries, that indeed looks good! Might switch myself too ;-)
